# Generated by Django 2.2.3 on 2019-08-18 01:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('user', models.OneToOneField(default='none', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_new', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='StartTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Starting Times',
            },
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine', models.CharField(max_length=50)),
                ('shift', models.TextField()),
                ('job', models.TextField()),
                ('quantity', models.TextField()),
                ('date', models.DateField()),
                ('in_question', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Production Lots',
            },
        ),
        migrations.CreateModel(
            name='HourlyProduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine', models.CharField(max_length=200)),
                ('hard_quantity', models.TextField(default='', max_length=200, null=True)),
                ('counter_quantity', models.TextField(default='', max_length=200, null=True)),
                ('job', models.TextField(default='', max_length=50, null=True)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Statuses',
            },
        ),
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('old_values', models.TextField(max_length=2000)),
                ('change_type', models.CharField(max_length=50)),
                ('changed_model', models.TextField(max_length=20)),
                ('changed_id', models.TextField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Logged Changes',
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.TextField(max_length=50)),
                ('job', models.CharField(max_length=20)),
                ('machine', models.CharField(max_length=50)),
                ('order_quantity', models.TextField(default=None, max_length=10, null=True)),
                ('possible_quantity', models.TextField(default=None, max_length=10, null=True)),
                ('remaining_quantity', models.TextField(default=None, max_length=10, null=True)),
                ('weight_recieved', models.TextField(default=None, max_length=10, null=True)),
                ('weight_length', models.TextField(default=None, max_length=10, null=True)),
                ('weight_quantity', models.TextField(default=None, max_length=10, null=True)),
                ('oal', models.TextField(default=None, max_length=10, null=True)),
                ('cut_off', models.TextField(default=None, max_length=10, null=True)),
                ('main_facing', models.TextField(default=None, max_length=10, null=True)),
                ('sub_facing', models.TextField(default=None, max_length=10, null=True)),
                ('heat_lot', models.TextField(default=None, max_length=30, null=True)),
                ('cycle_time', models.TextField(default=None, max_length=10, null=True)),
                ('bars', models.TextField(default=None, max_length=250, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Parts',
                'unique_together': {('user', 'machine', 'job')},
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine', models.CharField(max_length=50)),
                ('current_job', models.TextField(default='', max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Machines',
                'unique_together': {('user', 'machine')},
            },
        ),
    ]
