# Generated by Django 2.2.3 on 2019-07-24 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='changelog',
            name='change_type',
            field=models.CharField(default='c', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='changelog',
            name='changed_id',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='changed_model',
            field=models.TextField(max_length=20),
        ),
    ]
